### ISSUE TITLE
Kaydetme dönüşü

### ISSUE THREAD

**Issue by emresaracoglu** [emresenturk/ContentEditable#1]
Merhaba,

Düzeltilen metni, kaydetme ile JSON olarak dönüşü nasıl sağlanabilir?

Teşekkürler

**Comment by emresenturk** [comment]
Article olarak kullandığınız DOM elementinin **innerHTML** propertysini kullanabilirsiniz mesela.
```
var obj = { "articleContent": element.innerHTML }
```
gibi.

**Comment by emresaracoglu** [comment]
Anladım, peki teşekkür ederim.
